const fs = require('fs');
const path = require('path');

const components = {
  'layout/Navbar.tsx': `export default function Navbar() { return <nav className="p-4 flex justify-between bg-zinc-900 border-b border-zinc-800 text-white"><div className="font-bold text-[#1D9E75]">DSA Tracker</div><div><a href="/arena" className="mr-4">Arena</a><button className="bg-[#1D9E75] px-4 py-1 rounded-full text-sm font-bold">Install</button></div></nav>; }`,
  'layout/Footer.tsx': `export default function Footer() { return <footer className="p-4 text-center text-zinc-500 border-t border-zinc-800 mt-20">Built for exactly what you asked.</footer>; }`,
  'shared/UserAvatar.tsx': `export default function UserAvatar({ user }: any) { return <div className="w-10 h-10 rounded-full bg-zinc-800 flex items-center justify-center font-bold">{user?.username?.[0] || 'U'}</div>; }`,
  'shared/StreakBadge.tsx': `export default function StreakBadge({ streak }: { streak: number }) { return <span className="bg-orange-500/10 text-orange-400 px-2 py-1 flex items-center gap-1 rounded text-xs font-bold">🔥 {streak}</span>; }`,
  'shared/DifficultyBadge.tsx': `export default function DifficultyBadge({ diff }: { diff: string }) { const color = diff==='Hard'?'text-red-400 bg-red-400/10':diff==='Medium'?'text-amber-400 bg-amber-400/10':'text-green-400 bg-green-400/10'; return <span className={\`text-xs px-2 py-1 rounded \${color}\`}>{diff}</span>; }`,
  'battle/BattleCard.tsx': `import { motion } from 'framer-motion'; export default function BattleCard({ battle }: any) { return <motion.div initial={{opacity:0, y:20}} animate={{opacity:1, y:0}} className="bg-[#111] border-l-4 border-[#1D9E75] p-4 rounded max-w-sm"><h3 className="font-bold text-white">{battle.title || (battle.creatorUsername + "'s Battle")}</h3><div className="text-zinc-400 text-sm">{battle.playersJoined}/{battle.maxPlayers} joined</div></motion.div>; }`,
  'battle/BattleLeaderboard.tsx': `export default function BattleLeaderboard({ players }: any) { return <div className="bg-[#111] p-4 rounded"><h2 className="text-xl font-bold mb-4 text-[#1D9E75]">Leaderboard</h2>{players?.map((p:any, i:number) => <div key={i} className="flex justify-between items-center py-2 text-white border-b border-zinc-800"><span>{p.username}</span><span className="font-mono">{p.score} pts</span></div>)}</div>; }`,
  'battle/ActivityFeed.tsx': `import { motion } from 'framer-motion'; export default function ActivityFeed({ activities }: any) { return <div className="bg-[#111] p-4 rounded"><h2 className="text-xl text-[#1D9E75] font-bold mb-4">Live Feed</h2><div className="space-y-3">{activities?.map((a:any, i:number) => <motion.div initial={{opacity:0, x:20}} animate={{opacity:1, x:0}} key={i} className="text-sm text-zinc-300"><strong>{a.username}</strong> solved {a.questionName} <span className="text-xs px-1 bg-zinc-800 rounded">{a.difficulty}</span></motion.div>)}</div></div>; }`,
  'battle/ScoreBreakdown.tsx': `export default function ScoreBreakdown({ stats }: any) { return <div className="flex gap-2"><div className="flex-1 bg-red-500/10 text-red-500 p-2 text-center rounded"><div className="font-bold">{stats?.hard||0}</div><div className="text-xs">Hard</div></div><div className="flex-1 bg-amber-500/10 text-amber-500 p-2 text-center rounded"><div className="font-bold">{stats?.medium||0}</div><div className="text-xs">Med</div></div><div className="flex-1 bg-green-500/10 text-green-500 p-2 text-center rounded"><div className="font-bold">{stats?.easy||0}</div><div className="text-xs">Easy</div></div></div>; }`,
  'battle/ParticipantCard.tsx': `import StreakBadge from '../shared/StreakBadge'; import UserAvatar from '../shared/UserAvatar'; export default function ParticipantCard({ player }: any) { return <div className="flex items-center gap-3 p-3 bg-zinc-900 rounded"><UserAvatar user={player} /><div><div className="font-bold text-white">{player.username}</div><StreakBadge streak={player.currentStreak} /></div></div>; }`,
  'battle/AcceptChallengeBox.tsx': `export default function AcceptChallengeBox({ onJoin }: any) { return <div className="border border-[#1D9E75] bg-[#1D9E75]/10 p-6 rounded text-center"><h3 className="font-bold text-xl text-white mb-2">Join this battle</h3><p className="text-sm text-zinc-400 mb-4">Requires GitHub login</p><button onClick={onJoin} className="bg-[#1D9E75] text-white font-bold py-3 px-6 rounded-full w-full">⚔️ Accept Challenge</button></div>; }`,
  'arena/BattleWall.tsx': `import BattleCard from '../battle/BattleCard'; export default function BattleWall({ battles }: any) { return <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{battles?.map((b:any, i:number) => <BattleCard key={i} battle={b} />)}</div>; }`,
  'arena/StatsStrip.tsx': `export default function StatsStrip({ stats }: any) { return <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8"><div className="bg-[#111] p-4 text-center rounded"><div className="text-2xl font-black text-green-500">{stats?.liveBattles||0}</div><div className="text-xs text-zinc-500 uppercase tracking-widest">Live Battles</div></div><div className="bg-[#111] p-4 text-center rounded"><div className="text-2xl font-black text-white">{stats?.totalFighters||0}</div><div className="text-xs text-zinc-500 uppercase tracking-widest">Active Fighters</div></div><div className="bg-[#111] p-4 text-center rounded"><div className="text-2xl font-black text-amber-500">{stats?.openToJoin||0}</div><div className="text-xs text-zinc-500 uppercase tracking-widest">Open to join</div></div><div className="bg-[#111] p-4 text-center rounded"><div className="text-2xl font-black text-red-500">{stats?.eliminatedToday||0}</div><div className="text-xs text-zinc-500 uppercase tracking-widest">Eliminated</div></div></div>; }`,
  'arena/FilterBar.tsx': `export default function FilterBar() { return <div className="flex gap-4 border-b border-zinc-800 pb-2 mb-8 text-sm"><button className="text-[#1D9E75] border-b-2 border-[#1D9E75] pb-2 font-bold">All</button><button className="text-zinc-500 pb-2">Open</button><button className="text-zinc-500 pb-2">Streak</button></div>; }`
};

Object.entries(components).forEach(([filepath, content]) => {
  const fullPath = path.join(__dirname, 'src/components', filepath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content);
});

console.log("Built component skeletons!");
